name: Deploy pages
on: push
jobs:
  deploy:
    run-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Install slidev
        run: npm i -g @slidev/cli
      - name: Install for PDF
        run: npm i -D playwrite-chromium
      - name: Build
        run: slidev build --base /text_splitting
      - name: Deploy pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: dist
        env:
          GITHIB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
